In [1]:
import pandas as pd

In [8]:
trace_file = '../datasets/mawi_packet_trace_1.csv'
packets = pd.read_csv(trace_file)

In [9]:
packets

,timestamp,src_ip,dst_ip,src_port,dst_port,protocol,pkt_size
0,1688187600,46.25.179.131,202.249.92.15,15,4321,6,54
1,1688187600,202.249.92.28,46.25.179.131,16,19147,6,66
2,1688187600,202.249.92.28,46.25.179.131,16,19147,6,66
3,1688187600,128.201.56.18,202.249.90.150,22,625,6,74
4,1688187600,128.201.56.18,202.249.90.150,22,625,6,54
...,...,...,...,...,...,...,...
500599,1688187605,202.249.93.106,167.178.165.164,3074,7433,6,66
500600,1688187605,202.249.93.58,46.25.179.131,3074,7490,6,66
500601,1688187605,202.249.93.58,46.25.179.131,3074,7490,6,66
500602,1688187605,202.249.91.134,46.25.179.131,3074,7520,6,66
500603,1688187605,202.249.91.134,46.25.179.131,3074,7520,6,66

In [18]:
packets['src_ip'].value_counts().head(50)

src_ip
167.178.165.164    26075
46.25.179.131      23621
160.240.216.161    16687
223.204.131.39     13989
138.41.30.68       10845
8.1.21.190          9123
163.37.238.147      8896
185.250.95.163      7636
203.115.134.230     7386
203.115.138.80      5217
220.8.145.60        4324
104.147.254.159     4169
198.86.157.78       4119
203.115.132.54      3882
216.238.230.18      3718
202.249.90.150      3608
202.11.251.69       3545
137.61.67.250       2966
54.21.171.5         2919
89.122.37.5         2714
209.54.27.38        2603
8.2.127.247         2491
8.1.60.1            2463
94.148.194.81       2361
202.11.248.134      2315
104.150.22.33       2285
60.219.144.251      2261
45.100.248.16       2228
172.33.201.222      2219
104.150.21.189      2196
209.54.27.84        2133
137.61.67.246       2124
185.42.140.133      2121
202.11.248.242      2109
38.78.227.158       2064
66.230.255.218      2008
139.188.186.55      1986
137.61.67.254       1933
104.150.21.239      1905
172.33.201.233      1873
117.199.74.109      1734
203.115.141.159     1731
198.127.38.100      1690
165.30.152.207      1633
142.250.165.170     1590
137.61.67.255       1518
89.144.24.150       1452
182.140.106.150     1424
153.7.178.172       1403
115.75.57.24        1342
Name: count, dtype: int64

In [15]:
packets['dst_ip'].value_counts().head(10)

dst_ip
150.161.6.133      61969
167.178.165.164    54661
46.25.179.131      45256
163.37.238.147     23556
163.37.12.250      10891
180.65.57.101       6846
203.115.130.231     6405
203.115.138.80      6303
203.115.134.47      5287
45.100.248.16       4974
Name: count, dtype: int64

In [17]:
packets[packets['src_ip'] == packets['dst_ip']]

Empty DataFrame
Columns: [timestamp, src_ip, dst_ip, src_port, dst_port, protocol, pkt_size]
Index: []

In [5]:
flows_file = '../datasets/flows_2.csv'
flows = pd.read_csv(flows_file)

In [6]:
flows

,start_time,end_time,protocol,src_port,dst_port,pkt_size_1,pkt_size_2,pkt_size_3,pkt_size_4,pkt_size_5,...,7_pkt_size,7_pkt_max_iat,7_pkt_mean_iat,7_pkt_duration,flow_size,flow_pkt_count,flow_max_iat,flow_mean_iat,flow_duration,elephant
0,1.688188e+09,1.688188e+09,6.0,1999.0,54524.0,66.0,66.0,66.0,66.0,66.0,...,462.0,19.0,12.28125,44.0,792.0,12.0,19.0,6.977539e+00,85.0,0.0
1,1.688188e+09,1.688188e+09,1.0,0.0,0.0,70.0,70.0,70.0,70.0,70.0,...,490.0,0.0,0.00000,0.0,592410.0,8463.0,1.0,3.231174e-27,92.0,1.0
2,1.688188e+09,1.688188e+09,17.0,50005.0,3479.0,183.0,191.0,196.0,179.0,171.0,...,1265.0,0.0,0.00000,0.0,841789.0,4697.0,1.0,4.547474e-13,92.0,1.0
3,1.688188e+09,1.688188e+09,6.0,44734.0,443.0,54.0,54.0,54.0,54.0,0.0,...,216.0,4.0,2.37500,6.0,216.0,4.0,4.0,2.375000e+00,6.0,0.0
4,1.688188e+09,1.688188e+09,6.0,43332.0,3128.0,54.0,0.0,0.0,0.0,0.0,...,54.0,0.0,0.00000,0.0,54.0,1.0,0.0,0.000000e+00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1815567,1.688188e+09,1.688188e+09,6.0,80.0,12256.0,66.0,66.0,0.0,0.0,0.0,...,132.0,0.0,0.00000,0.0,132.0,2.0,0.0,0.000000e+00,0.0,0.0
1815568,1.688188e+09,1.688188e+09,1.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,...,60.0,0.0,0.00000,0.0,60.0,1.0,0.0,0.000000e+00,0.0,0.0
1815569,1.688188e+09,1.688188e+09,1.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,...,60.0,0.0,0.00000,0.0,60.0,1.0,0.0,0.000000e+00,0.0,0.0
1815570,1.688188e+09,1.688188e+09,6.0,44843.0,2375.0,54.0,0.0,0.0,0.0,0.0,...,54.0,0.0,0.00000,0.0,54.0,1.0,0.0,0.000000e+00,0.0,0.0
1815571,1.688188e+09,1.688188e+09,6.0,50355.0,43527.0,58.0,0.0,0.0,0.0,0.0,...,58.0,0.0,0.00000,0.0,58.0,1.0,0.0,0.000000e+00,0.0,0.0

In [ ]:
def set_ips(data, ips):
    # Create a dictionary to store flow information
    flows = {}
    
    # Iterate through the dataset
    for index, row in data.iterrows():
        # Extract relevant packet attributes 
        timestamp = row['timestamp']
        src_ip = row['src_ip']
        dst_ip = row['dst_ip']
        src_port = row['src_port']
        dst_port = row['dst_port']
        protocol = row['protocol']
        pkt_size = row['pkt_size']

        # Create a unique key for the flow based on the packet attributes
        flow_key = (src_ip, dst_ip, src_port, dst_port, protocol)

        # Check if the flow already exists in the dictionary
        if flow_key in flows:
            flows[flow_key]['flow_size'] += pkt_size
            flows[flow_key]['flow_pkt_count'] += 1

            # maximum inter arrival time
            if flows[flow_key]['flow_max_iat'] < row['timestamp'] - flows[flow_key]['end_time']:
                flows[flow_key]['flow_max_iat'] = row['timestamp'] - flows[flow_key]['end_time']

            # mean inter arrival time
            if flows[flow_key]['flow_mean_iat'] > 0:
                flows[flow_key]['flow_mean_iat'] = np.mean([flows[flow_key]['flow_mean_iat'], (row['timestamp'] - flows[flow_key]['end_time'])])                
            else:
                flows[flow_key]['flow_mean_iat'] = row['timestamp'] - flows[flow_key]['end_time']
                
            # flow duration
            flows[flow_key]['flow_duration'] = row['timestamp'] - flows[flow_key]['start_time']

            # update elephant or mice
            if flows[flow_key]['flow_size'] > elephant_flow_threshold:
                flows[flow_key]['elephant'] = 1

            flows[flow_key]['end_time'] = row['timestamp']
            
        else:
            # Create a new entry for the flow
            if pkt_size_col > 1:
                flows[flow_key] = {
                    'start_time': timestamp,
                    'end_time': timestamp,
                    'protocol': protocol,
                    'src_port': src_port,
                    'dst_port': dst_port,
                    'pkt_size_1': pkt_size,
                    **pkt_size_columns,
                    f'{pkt_size_col}_pkt_size': pkt_size,
                    f'{pkt_size_col}_pkt_max_iat': 0,
                    f'{pkt_size_col}_pkt_mean_iat': 0,
                    f'{pkt_size_col}_pkt_duration': 0,
                    'flow_size': pkt_size,
                    'flow_pkt_count': 1,
                    'flow_max_iat': 0,
                    'flow_mean_iat': 0,
                    'flow_duration': 0,
                    'elephant': 0,
                }

            else:
                flows[flow_key] = {
                    'protocol': protocol,
                    'src_port': src_port,
                    'dst_port': dst_port,
                    'pkt_size_1': pkt_size,
                    'flow_size': pkt_size,
                    'flow_pkt_count': 1,
                    'flow_max_iat': 0,
                    'flow_mean_iat': 0,
                    'flow_duration': 0,
                    'elephant': 0,
                }

        
        if index % 100000 == 0:
            print(f'{index} rows processed')
        
    # Output csv file
    # Convert dictionary to dataframe
    data_features = pd.DataFrame.from_dict(flows)

    # Transpose the dataframe
    data_features = data_features.transpose()
    
    # Remove index
#     data_features = data_features.reset_index(drop=True, inplace=True)

    return data_features